projects:
  - name: openEuler
    owner: openeuler
    repo: openEuler-portal
    project_type: portal
    repo_url: https://gitcode.com/openeuler/openEuler-portal.git
    branch: master
    framework: VitePress
    build_dir: app/.vitepress/dist
    accessible_routes:
      - /zh/**/*
      - /en/**/*
    ignore_routes:
      - /(zh|en)/(other/)?(blog|news)
    build_script: build:geo
    seo_config_dir:
      tdk: .geo/tdks
      schema: .geo/jsonld
    home:
      - https://www.openeuler.org/
      - https://www.openeuler.openatom.cn/
  - name: openEuler-docs
    owner: openeuler
    repo: docs-website
    project_type: docs
    repo_url: https://gitcode.com/openeuler/docs-website.git
    branch: master
    framework: VitePress
    build_dir: app/.vitepress/dist
    skip_check:
      - tdk
      - schema
      - sitemap-coverage
    home:
      - https://docs.openeuler.org/
      - https://docs.openeuler.openatom.cn/
  - name: openGauss
    owner: opengauss
    repo: website
    project_type: portal
    repo_url: https://gitcode.com/opengauss/website.git
    branch: v2
    framework: VitePress
    build_dir: app/.vitepress/dist
    accessible_routes:
      - /zh/**/*
      - /en/**/*
    ignore_routes:
      - /(zh|en)/(blogs|search|notification)
      - /en/user-practice
    build_script: build
    seo_config_dir:
      tdk: .geo/tdk
      schema: .geo/jsonld
    home:
      - https://opengauss.org/
  - name: openGauss-docs
    owner: opengauss
    repo: docs
    project_type: docs
    repo_url: https://gitcode.com/opengauss/docs-website.git
    branch: v2
    framework: VitePress
    build_dir: app/.vitepress/dist
    skip_check:
      - tdk
      - schema
      - sitemap-coverage
    home:
      - https://docs.opengauss.org/
  - name: MindSpore
    owner: mindspore
    repo: mindspore-portal
    repo_url: https://gitcode.com/mindspore/mindspore-portal.git
    branch: master
    framework: Nuxt
    build_dir: packages/website/.output/public
    build_script: generate:geo
    accessible_routes:
      - /
    ignore_routes:
      - /?(technology-blogs|search|online-showroom)/?(zh|en)
    seo_config_dir:
      tdk: .geo/tdk
      schema: .geo/jsonld
    home:
      - https://www.mindspore.cn/
  - name: HiFloat
    owner: hifloat
    repo: hifloat-portal
    repo_url: https://gitcode.com/hifloat/hifloat-portal
    branch: main
    framework: Nuxt
    build_dir: .output/public
    build_script: generate
    accessible_routes:
      - /
    ignore_routes:
      - /?(technology-blogs|search|online-showroom)/?(zh|en)
    seo_config_dir:
      tdk: .geo/tdk
      schema: .geo/jsonld
    home:
      - https://hifloat.gccorg.com/
